### ISSUE TITLE
Typescript to Javascript

### ISSUE THREAD

**Issue by Yam3101** [MRJonas343/BEESMRT#1]
Some files withb TS are not supported at all, so whenever you change the .tsx to .jsx it even works and any trouble happens, btw, i'll try to find a solution but as I saw that's a reason why Tailwind and React is having some bugs, cause we're compiling in TS

**Comment by MRJonas343** [comment]
Not worrys about why React is having issues with Tailwind, it is happening because I made the configurations by my own, but when l migrate the project to NextJs the issues are going to dissapeard
